spring:
  application:
    name: Config-Default
eureka:
  instance:
    hostname: localhost
    ip-address: true
    
 
  client:
    fetchRegistry: true
    registerWithEureka: true
  
  server:
    waitTimeInMsWhenSyncEmpty: 0
